"""ZIP generation and filesystem persistence."""

import io
import os
import zipfile

from forge.config import settings


def create_zip(source_files: dict[str, str], test_files: dict[str, str]) -> bytes:
    """Generates a standard project structure in an in-memory ZIP."""
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        # Add sources
        for name, content in source_files.items():
            zf.writestr(name, content)
        # Add tests
        for name, content in test_files.items():
            zf.writestr(f"tests/{name}", content)

        # Add metadata
        zf.writestr("requirements.txt", "# Standard Library Only\npytest\n")
        zf.writestr("README.md", "# Generated by FORGE\n\nRun with `python main.py` or `pytest`.")

    return buffer.getvalue()


def store_zip(request_id: str, zip_bytes: bytes) -> str:
    """Saves the ZIP to the local download directory."""
    os.makedirs(settings.DOWNLOAD_DIR, exist_ok=True)
    path = os.path.join(settings.DOWNLOAD_DIR, f"{request_id}.zip")
    with open(path, "wb") as f:
        f.write(zip_bytes)
    return f"/api/download/{request_id}"
